"""pr_opener.py — Commits + opens GitHub PR. One API call for PR body."""
from __future__ import annotations
import re
import subprocess
from .state import AgentState
from devrag.llm.client import chat
from devrag.tools.github_client import commit_changes, create_pull_request
from rich.console import Console

console = Console()


def _has_changes(repo_path: str) -> bool:
    """Check if there are any uncommitted changes in the repo."""
    result = subprocess.run(
        "git status --porcelain",
        shell=True, cwd=repo_path, capture_output=True, text=True
    )
    return bool(result.stdout.strip())


def pr_opener_node(state: AgentState) -> dict:
    console.print("[bold cyan]Opening pull request...[/bold cyan]")

    # Check if there are any changes to commit
    if not _has_changes(state["repo_path"]) and not state.get("code_changes"):
        console.print("  [yellow]No changes to commit - skipping PR[/yellow]")
        return {
            "branch_name": None, 
            "pr_url": None, 
            "total_tokens": state.get("total_tokens", 0),
            "error": "No code changes were made"
        }

    branch = "devrag/fix-{}-{}".format(
        state["issue_number"],
        re.sub(r"[^a-z0-9]+", "-", state["issue_title"].lower())[:40],
    )

    commit_changes(state["repo_path"], branch,
                   f"fix: resolve #{state['issue_number']} - {state['issue_title']}\n\nGenerated by DevRAG")

    changes_list = "\n".join(f"- `{c['file']}`" for c in state.get("code_changes", [])) or "- (none tracked)"

    messages = [
        {"role": "system", "content": "Write a concise GitHub PR description in markdown. Include: Summary, Changes, Testing, and 'Closes #N'. Be brief."},
        {"role": "user",   "content":
            f"Issue #{state['issue_number']}: {state['issue_title']}\n"
            f"{state['issue_body'][:400]}\n\nFiles changed:\n{changes_list}"},
    ]
    pr_msg, _ = chat(messages, max_tokens=350, fast=True)

    pr_url = create_pull_request(
        owner=state["repo_owner"], repo_name=state["repo_name"],
        repo_path=state["repo_path"], branch_name=branch,
        issue_number=state["issue_number"], issue_title=state["issue_title"],
        pr_body=pr_msg.content or "",
    )

    console.print(f"  [green]PR: {pr_url}[/green]")
    return {"branch_name": branch, "pr_url": pr_url, "total_tokens": state.get("total_tokens", 0)}